export default {
  IP_API_GET_LOCATION_URL: process.env.IP_API_GET_LOCATION_URL,
  OW_API_KEY: process.env.OW_API_KEY,
  OW_GET_LOCATION_URL: process.env.OW_GET_LOCATION_URL,
  OW_GET_CURRENT_WEATHER_URL: process.env.OW_GET_CURRENT_WEATHER_URL,
  OW_GET_FORECAST_URL: process.env.OW_GET_FORECAST_URL,
};
